version: "3"
services:
  nginx:
    image: nginxproxy
    networks: bridge
    depends_on:
       - backend
       - backend2
    ports:
       - 3030:80

    volumes:
       - C:\DimitarS\default.conf:/etc/nginx/conf.d/default.conf
   
  backend: 
    image: backend
    networks: bridge
    ports: 
       - 3006:80
 
  backend2:
    image: backend2
    networks: bridge
    ports: 
       - 4001:80
volumes:
 loadbalancer:
  driver: local
